### ISSUE TITLE
[BUG] When the title bar is hidden, a strange thing sometimes appears

### ISSUE THREAD

**Issue by Xiaokang2022** [Zingzy/hPyT#41] opened 2024-12-28 12:20 UTC
**Describe the bug**

When the title bar is hidden, a strange thing sometimes appears:

<img width="153" alt="2024-12-28 201415" src="https://github.com/user-attachments/assets/c5c2b1fa-f275-4b1b-96d2-b3681c6b6483" />

You can see a gray bar appear on the top.

Reproduction method:

This will happen when you launch the program, click on the window, then click on the system task bar and repeat everything in between.

## Environment

```bash
$ python -m platform
Windows-11-10.0.26100-SP0

$ python --version
3.13.0

$ pip show hPyT
Name: hPyT
Version: 1.3.6
Summary: Hack Python Titlebar - A package to manipulate windows and titlebar of GUI applications made using python.
Home-page: https://github.com/zingzy/hPyT
Author: zingzy
Author-email: 
License: MIT
Location: C:\Software\Python313\Lib\site-packages
Requires: 
Required-by:
```

## Code

```python
import tkinter

import hPyT

root = tkinter.Tk()
hPyT.title_bar.hide(root)
root.mainloop()
```

**Comment by Zingzy** [comment] 2024-12-28 18:19
Closing this because there is a new issue (#42) for the same

**Comment by Xiaokang2022** [comment] 2024-12-29 06:18
@Zingzy , This issue is different from the other one, please take a closer look, thank you.

**Comment by Zingzy** [comment] 2024-12-29 08:22
@Xiaokang2022 Thanks for pointing this issue out, I was able to find the root cause of this issue... The issue occurs because the `WM_NCACTIVATE` and `WM_NCPAINT` messages, which control the non-client area (including the title bar), were not being handled explicitly. When the window is activated or deactivated, Windows attempts to paint the non-client area (title bar), causing a white patch to appear temporarily. I will fix this issue in the next update

**Closed** 2024-12-29 19:54 UTC
Labels: bug
